site_name: My Super Cool Project
site_url: https://sandeep280993.github.io/masandeep/
site_author: The Awesome Team
site_description: This site contains my portfolio related to API documentation.
repo_url: https://github.com/sandeep280993/masandeep
repo_name: masandeep 
edit_uri: ""
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.top
    # - toc.integrate 
    - content.code.copy
use_directory_urls: true
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  
plugins:
  - search
  - tags
nav: 
  - Home : index.md
  - About : about/index.md
  - Portfolio :
    - API reference : 
      - Mock Credit Card APIs : portfolio/mock-api-doc.md
      - Create card : portfolio/create.md
      - Delete card : portfolio/delete.md
      - Update card : portfolio/update.md
      - Retrieve card : portfolio/retrieve.md
      - Retrieve all cards : portfolio/retrieve-all.md
  - AI projects : 
    - AI projects: ai-projects/index.md
    - Ai-projects: ai-projects/ai-project.md
    - Offline markdown previewer: ai-projects/Gemini-style-mdpreview.md
    - Video to doc convertoer: ai-projects/vdo-to-doc-converter.md
